server:
  port: 8030
  servlet:
    context-path: /volt

logging:
  level:
    org.springframework: INFO
    au.com.chen: DEBUG

spring:
  kafka:
    consumer:
      group-id: my-group
      auto-offset-reset: earliest
    # change this property if you are using your own
    # Kafka cluster or your Docker IP is different
    bootstrap-servers: localhost:9092

app:
  topic-name: my-topic

security:
  oauth2:
    client:
      client-id: client
      client-secret: password
      scope: read,write
      auto-approve-scopes: '.*'